Update Wisdom
wisp-forest/owo-lib pull request #195
Opened 2023-11-29 20:40 UTC by Noaaan

This PR updates Wisdom, resolving #174, as well as adding a few more lines to Wisdom.

2023-12-02 01:52 UTC, gliscowo requested changes

2023-12-02 01:52 UTC, gliscowo commented on src/main/java/io/wispforest/owo/util/Wisdom.java
> -            "idwtialsimmoedm - I didn't want to install a library so I made my own enchantment descriptions mod",
Why did you remove the acronym here? It must absolutely stay, otherwise the entire joke is lost

2023-12-02 22:33 UTC, BasiqueEvangelist commented on src/main/java/io/wispforest/owo/util/Wisdom.java
> -            "idwtialsimmoedm - I didn't want to install a library so I made my own enchantment descriptions mod",
i mean it's effectively isdwitaosdmelodelsdm adveritisting

2023-12-09 22:13 UTC, gliscowo approved these changes

2023-12-09 22:13 UTC, merged