itemgroup: turn OwoItemSettings into an interface injection
wisp-forest/owo-lib pull request #249
Opened 2024-06-16 21:46 UTC by BasiqueEvangelist

Since this breaks source and binary compatibility, this should probably be scheduled for a major release

2024-07-02 06:16 UTC, Jab125 commented
Might be worth namespacing the injected methods, i.e. `group` to `owo$group`.

2024-07-02 14:52 UTC, BasiqueEvangelist commented
I don't see any point in namespacing interface injected methods, especially the ones that have owo-specific types in their descriptors

2024-07-05 22:06 UTC, gliscowo requested changes

2024-07-05 22:06 UTC, gliscowo commented on src/main/java/io/wispforest/owo/mixin/itemgroup/ItemSettingsMixin.java
> +    private BiConsumer<Item, ItemGroup.Entries> owo$stackGenerator = (item, stacks) -> stacks.add(item.getDefaultStack());
🤨

2024-07-21 19:50 UTC, BasiqueEvangelist commented on src/main/java/io/wispforest/owo/mixin/itemgroup/ItemSettingsMixin.java
> +    private BiConsumer<Item, ItemGroup.Entries> owo$stackGenerator = (item, stacks) -> stacks.add(item.getDefaultStack());
ficksed

2024-07-21 19:55 UTC, merged