Sizing.Random()™
wisp-forest/owo-lib pull request #265
Opened 2024-07-11 23:10 UTC by chyzman

also updated wisdom

2024-07-11 23:12 UTC, BasiqueEvangelist commented on src/main/java/io/wispforest/owo/util/Wisdom.java
> +            "blod: I think I need to take a book out of your page"
```suggestion
            "blod: I think I need to take a book out of your page",
            "blod: he her"
```

2024-07-11 23:38 UTC, gliscowo requested changes

2024-07-11 23:38 UTC, gliscowo commented on src/main/java/io/wispforest/owo/ui/core/Color.java
> +     * @apiNote Don't tell glisco about this
Noted, won't do

2024-07-11 23:38 UTC, gliscowo commented on src/main/java/io/wispforest/owo/ui/core/Sizing.java
> +         * @apiNote Can crash if put on a component that isn't a container
More like, any component that doesn't support content sizing - scroll containers come to mind (at least on one of their axes)

2024-07-11 23:38 UTC, gliscowo commented on src/main/java/io/wispforest/owo/ui/core/Sizing.java
> +         * @author chyzman
No need for an author tag on every method if there's already one on the class

2024-07-11 23:40 UTC, BasiqueEvangelist commented on src/main/java/io/wispforest/owo/ui/core/Color.java
> +     * @apiNote Don't tell glisco about this
hey @gliscowo you might wanna see this

2024-07-12 00:02 UTC, gliscowo commented on src/main/java/io/wispforest/owo/ui/core/Sizing.java
> +            return MathHelper.lerp(this.delta, this.first.inflate(space, contentSizeFunction), this.second.inflate(space, contentSizeFunction));
ngl, feels like u pressed ctrl+alt+l a bit too hard

2024-07-12 00:04 UTC, gliscowo approved these changes
Finally, the perfect PR

2024-07-12 00:06 UTC, merged