Add API for inspecting planned tag injections
wisp-forest/owo-lib pull request #58
Opened 2022-10-04 22:09 UTC by lukebemish

For a mod of mine (Dynamic Asset Generator), I need to be able to inspect tags before tags are loaded, for various reasons. Generally, this can be done by just loading the data packs in question using a custom tool; however, as owo-lib injects tag entries directly into the tag loader, this does not work. I can build compatibility on my end if I have some way to look at planned tag injections before they are actually injected; this PR gives a way to do that.

Currently, the implementation uses unmodifiable maps and sets; however, there are other ways it could be implemented. Let me know if you'd like me to change stuff.

2022-10-08 23:15 UTC, gliscowo requested changes
I believe the concept of this addition is perfectly valid, although I'm not super happy with the implementation. Ideally you would just make a separate, private field (something like `ADDITIONS_VIEW`) which is simply `Collections.unmodifiableMap(ADDITIONS)`. There is no need to create a new object every single time, plus this avoids the rather clunky inline class

2022-10-08 23:17 UTC, lukebemish commented
I can move it to a field - unfortunately, you'll still need the inline class, because an unmodifiable map will still make the sets in the values of the map modifiable.

2022-10-09 11:05 UTC, BasiqueEvangelist commented
Can't you get the tag data by making your own resource manager and reloading it?

2022-10-09 12:05 UTC, lukebemish commented
In theory, yes, in practice, there's a lot of limitations there, as well as some potential performance worries, and it also tends to break other mods expectations.

2022-10-09 12:32 UTC, lukebemish commented
Additionally, it would hide some of the structure present in the raw JSON files that i look at, like replacement and whatnot.

2022-10-09 15:00 UTC, lukebemish commented
Alright, the unmodifiable view is stored in a private field now, so it won't reinstantiate every call. Still has to use the `ForwardingMap`, unless you can think of a better approach, since a normal unmodifiable map would still make the set values modifiable.

2022-10-10 05:35 UTC, gliscowo commented
After thinking about it again, I don't know if I quite understand what goal this PR is actually chasing. After all, the field containing all tag injections is already public - you could simply inspect it directly. I believe this is quite the specialty use-case and I can't really imagine other circumstances where someone needs to know this. Other than a potential argument about API stability, is there any reason to introduce this change?

2022-10-10 11:37 UTC, lukebemish commented
It's entirely about API stability. I don't want to rub into an issue down the road due to using the internal field

2022-10-24 20:39 UTC, gliscowo approved these changes

2022-10-24 20:39 UTC, merged